runtime: nodejs14
instance_class: F1 # F2
service: service-a

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 3

# manual_scaling:
#   instances: 2