name: Schoen deployen

on:
  push: 
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
    
    - uses: google-github-actions/setup-gcloud@v0.2.1
      with:
          project_id: modern-tech-training-331108
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
    
    - uses: google-github-actions/deploy-appengine@v0.4.0
      with:
          project_id: modern-tech-training-331108
          deliverables: app.yaml
